Apply pylint (#22)
* Add pylinter to pre-commit hook

* Apply pylinter suggestions to clean up code

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -7,20 +7,31 @@ NC='\033[0m'
 
 echo "Running Linters:"
 
-# Run tslint and get the output and return code
+# Run mypylint and get the output and return code
 mypylint=$(mypy --ignore-missing-imports src)
 ret_code=$?
 
 # If it didn't pass, announce it failed and print the output
 if [ $ret_code != 0 ]; then
 	printf "\n${RED}mypy linter failed:${NC}"
-	echo "$tslint\n"
+	echo "$mypylint\n"
 	pass=false
 else
 	printf "${GREEN}mypy linter passed.${NC}\n"
 fi
 
 #TODO: also call pylint
+pylint=$(pylint --rcfile=pylintrc src)
+ret_code=$?
+
+# If it didn't pass, announce it failed and print the output
+if [ $ret_code != 0 ]; then
+	printf "\n${RED}pylint linter failed:${NC}"
+	echo "$pylint\n"
+	pass=false
+else
+	printf "${GREEN}pylint linter passed.${NC}\n"
+fi
 
 # If there were no failures, it is good to commit
 if $pass; then
